[user]
name = "Zain Afzal"
email = "zain.afz@gmail.com"

[ui]
default-command = "status"

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_id(id)' = 'id.shortest()'
'format_short_signature(signature)' = 'signature.name()'

[aliases]
# While working with jj-git, use this to point main to the latest non-working-copy change
setmain = ["branch", "set", "main", "-r", "@-"]
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '-d', 'main']
push = ['git', 'push', '--all']
ig = ['git', 'init', '--git-repo=.']
