[user]
name = "Will Richardson"
email = "william.hamish@gmail.com"

[ui]
default-command = "status"
diff-editor = ":builtin"

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_id(id)' = 'id.shortest()'
'format_short_signature(signature)' = 'signature.name()'

[aliases]
ig = ['git', 'init', '--git-repo=.']

setmain = ["branch", "set", "main", "-r", "@-"]
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '-d', 'main']

cl = ['git', 'push', '-c', '@-']
push = ['git', 'push', '-b', 'glob:willhbr/push-*']
upload = ['git', 'push', '--all']
