[user]
name = "Will Richardson"
email = "will@willhbr.net"

[ui]
default-command = "status"
diff-editor = ":builtin"

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_id(id)' = 'id.shortest()'
'format_short_signature(signature)' = 'signature.name()'

[git]
push-branch-prefix = "willhbr/push-"

[aliases]
ig = ['git', 'init', '--git-repo=.']

setmain = ["branch", "set", "main", "-r", "@-"]
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '--skip-empty', '-d', 'main']

xl = ['log', '-r', 'all()']
pl = ['obslog', '-p']

cl = ['git', 'push', '-c', '@-']
push = ['git', 'push', '-b', 'glob:willhbr/push-*']
upload = ['git', 'push', '--all']

configure = ['config', 'edit', '--repo']
