[user]
name = 'Will Richardson'
email = 'will@willhbr.net'

[ui]
default-command = 'status'
diff-editor = ':builtin'

[colors]
'working_copy author' = 'bright white'
'author' = 'white'

[template-aliases]
'format_timestamp(ts)' = '''
if(
  ts.after("1 week ago"),
  ts.ago(),
  ts.format("%b %d, %Y %H:%M"))
'''
'format_short_id(id)' = 'id.shortest()'
'format_short_signature(signature)' = 'signature.name()'

[revsets]
log = '@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()'

[git]
push-bookmark-prefix = 'willhbr/push-'

[aliases]
ig = ['git', 'init', '--git-repo=.']

setmain = ['bookmark', 'set', 'main', '-r', '@-']
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '--skip-emptied', '-d', 'trunk()']

xl = ['log', '-r', 'all()']
pl = ['obslog', '-p']

cl = ['git', 'push', '-c', '@-']
push = ['git', 'push', '--all']

configure = ['config', 'edit', '--repo']

'..' = ['edit', '-r', '@-']
',,' = ['edit', '-r', '@+']
